float age=70;
if(age<0){;
  println("Aborted");
}else if (age<2){;
  println("Baby");
}else if (age<4){;
  println("Kleuter");
}else if (age<12){;
  println("Kind");
}else if (age<20){;
  println("Tiener");
}else if (age<25){;
  println("Adolecent");
}else if (age<40){;
  println("Volwassenen");
}else if (age<60){;
  println("Middle-aged");
}else if(age>=60){;
  println("Bejaard");
};
  
