size(600,100);
String leeg="";
String naam="Jade";
String zin="is mijn naam";
String extra="en mijn hobby is";
String intresse="boogschieten";
println(naam+" "+zin+" "+extra+" "+intresse+"!");
textSize(24);
fill(0);
text(naam+" "+zin+" "+extra+" "+intresse+"!",10,16);
